name: Update README everyday at 6:00

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '* 6 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Cache
        uses: actions/cache/@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Update README.md file
        run: |
          node index.js > README.md
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Noé
          author_email: nhenchoz122@icloud.com
          force: false
          signoff: false
          message: 'Update README.md file'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}